language: node_js
node_js:
    - "6"
services:
    - postgresql
    - rabbitmq
install:
    - npm install
before_script:
    # Create a database
    - psql -c 'create database users;' -U postgres
script:
    # Install the schema
    - npm run db:migrate
    # Test
    - npm test
after_script:
    - istanbul cover ./node_modules/mocha/bin/_mocha tests/**/*.test.js
    - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
env:
    - NODE_ENV=testing POSTGRESQL_HOST=localhost POSTGRESQL_PORT=5432 POSTGRESQL_USER=postgres POSTGRESQL_PASSWORD="" POSTGRESQL_DATABASE=users AMQP_HOST=localhost AMQP_PORT=5672 AMQP_VHOST=/ AMQP_USERNAME=guest AMQP_PASSWORD=guest
